import type { Source } from "@/lib/types";

export type SourceChrome = {
  handle: string;
  domain: string;
  mark: string;
  accent: string;
  accentSoft: string;
  chrome: string;
  /** Real site URL for native window / optional iframe */
  liveUrl: string;
  /**
   * iframe = page usually allows embedding
   * popup = platform blocks iframe; open real native window instead
   */
  embed: "iframe" | "popup";
  kind:
    | "lab"
    | "paper"
    | "blog"
    | "forum"
    | "repo"
    | "tweet"
    | "youtube"
    | "press";
};

export const sourceChrome: Record<Source, SourceChrome> = {
  OpenAI: {
    handle: "openai",
    domain: "openai.com/news",
    mark: "OAI",
    accent: "#10a37f",
    accentSoft: "rgba(16, 163, 127, 0.14)",
    chrome: "#0d1512",
    liveUrl: "https://openai.com/news",
    embed: "popup",
    kind: "lab",
  },
  Anthropic: {
    handle: "anthropic",
    domain: "anthropic.com/news",
    mark: "ANT",
    accent: "#d4a27f",
    accentSoft: "rgba(212, 162, 127, 0.14)",
    chrome: "#15110e",
    liveUrl: "https://www.anthropic.com/news",
    embed: "popup",
    kind: "lab",
  },
  "Google DeepMind": {
    handle: "deepmind",
    domain: "deepmind.google/discover",
    mark: "GDM",
    accent: "#4285f4",
    accentSoft: "rgba(66, 133, 244, 0.14)",
    chrome: "#0e1218",
    liveUrl: "https://deepmind.google/blog/",
    embed: "popup",
    kind: "lab",
  },
  "Meta AI": {
    handle: "metaai",
    domain: "ai.meta.com/blog",
    mark: "META",
    accent: "#0668e1",
    accentSoft: "rgba(6, 104, 225, 0.14)",
    chrome: "#0e1218",
    liveUrl: "https://ai.meta.com/blog/",
    embed: "popup",
    kind: "lab",
  },
  xAI: {
    handle: "xai",
    domain: "x.ai/news",
    mark: "xAI",
    accent: "#e7e9ea",
    accentSoft: "rgba(231, 233, 234, 0.1)",
    chrome: "#0a0a0a",
    liveUrl: "https://x.ai/news/",
    embed: "popup",
    kind: "lab",
  },
  DeepSeek: {
    handle: "deepseek",
    domain: "github.com/deepseek-ai",
    mark: "DS",
    accent: "#4d6bfe",
    accentSoft: "rgba(77, 107, 254, 0.14)",
    chrome: "#0e1220",
    liveUrl: "https://github.com/deepseek-ai",
    embed: "popup",
    kind: "lab",
  },
  Qwen: {
    handle: "qwen",
    domain: "qwenlm.github.io/blog",
    mark: "QW",
    accent: "#615ced",
    accentSoft: "rgba(97, 92, 237, 0.14)",
    chrome: "#101018",
    liveUrl: "https://qwenlm.github.io/blog/",
    embed: "popup",
    kind: "lab",
  },
  "Mistral AI": {
    handle: "mistral",
    domain: "mistral.ai/news",
    mark: "MIS",
    accent: "#ff8205",
    accentSoft: "rgba(255, 130, 5, 0.14)",
    chrome: "#14110c",
    liveUrl: "https://mistral.ai/news/",
    embed: "popup",
    kind: "lab",
  },
  Kimi: {
    handle: "kimi",
    domain: "kimi.com/blog",
    mark: "Ki",
    accent: "#1783ff",
    accentSoft: "rgba(23, 131, 255, 0.14)",
    chrome: "#0c1420",
    liveUrl: "https://www.kimi.com/blog",
    embed: "popup",
    kind: "lab",
  },
  MiniMax: {
    handle: "minimax",
    domain: "minimax.io/blog",
    mark: "MM",
    accent: "#ff6a00",
    accentSoft: "rgba(255, 106, 0, 0.14)",
    chrome: "#14100c",
    liveUrl: "https://www.minimax.io/blog",
    embed: "popup",
    kind: "lab",
  },
  "Prime Intellect": {
    handle: "primeintellect",
    domain: "primeintellect.ai/blog",
    mark: "PI",
    accent: "#f7f8f8",
    accentSoft: "rgba(247, 248, 248, 0.1)",
    chrome: "#0a0a0a",
    liveUrl: "https://www.primeintellect.ai/blog",
    embed: "popup",
    kind: "lab",
  },
  ByteDance: {
    handle: "bytedance",
    domain: "github.com/ByteDance-Seed",
    mark: "Byte",
    accent: "#fe2c55",
    accentSoft: "rgba(254, 44, 85, 0.14)",
    chrome: "#140a0e",
    liveUrl: "https://github.com/ByteDance-Seed",
    embed: "popup",
    kind: "lab",
  },
  "Black Forest Labs": {
    handle: "bfl",
    domain: "github.com/black-forest-labs",
    mark: "BFL",
    accent: "#7cff6b",
    accentSoft: "rgba(124, 255, 107, 0.12)",
    chrome: "#0c120e",
    liveUrl: "https://github.com/black-forest-labs",
    embed: "popup",
    kind: "lab",
  },
  "Thinking Machines": {
    handle: "thinkingmachines",
    domain: "thinkingmachines.ai/news",
    mark: "TM",
    accent: "#d0d6e0",
    accentSoft: "rgba(208, 214, 224, 0.1)",
    chrome: "#0f1011",
    liveUrl: "https://thinkingmachines.ai/news/",
    embed: "popup",
    kind: "lab",
  },
  "Hugging Face": {
    handle: "huggingface",
    domain: "huggingface.co/blog",
    mark: "HF",
    accent: "#ff9d0a",
    accentSoft: "rgba(255, 157, 10, 0.14)",
    chrome: "#16120a",
    liveUrl: "https://huggingface.co/blog",
    embed: "popup",
    kind: "lab",
  },
  arXiv: {
    handle: "arxiv",
    domain: "arxiv.org/list/cs.AI/recent",
    mark: "arX",
    accent: "#b31b1b",
    accentSoft: "rgba(179, 27, 27, 0.14)",
    chrome: "#140e0e",
    liveUrl: "https://arxiv.org/list/cs.AI/recent",
    embed: "iframe",
    kind: "paper",
  },
  "Tech Blog": {
    handle: "techblog",
    domain: "simonwillison.net",
    mark: "TB",
    accent: "#8a8f98",
    accentSoft: "rgba(138, 143, 152, 0.12)",
    chrome: "#101112",
    liveUrl: "https://simonwillison.net/",
    embed: "iframe",
    kind: "blog",
  },
  "Developer Community": {
    handle: "devcommunity",
    domain: "news.ycombinator.com",
    mark: "YC",
    accent: "#ff6600",
    accentSoft: "rgba(255, 102, 0, 0.14)",
    chrome: "#14100c",
    liveUrl: "https://news.ycombinator.com/",
    embed: "iframe",
    kind: "forum",
  },
  "GitHub · Articles": {
    handle: "github-articles",
    domain: "github.blog",
    mark: "GHa",
    accent: "#f0f6fc",
    accentSoft: "rgba(240, 246, 252, 0.08)",
    chrome: "#0d1117",
    liveUrl: "https://github.blog/ai-and-ml/",
    embed: "popup",
    kind: "blog",
  },
  "GitHub · Skills": {
    handle: "github-skills",
    domain: "github.com/topics/agent-skills",
    mark: "GHs",
    accent: "#a5d6ff",
    accentSoft: "rgba(165, 214, 255, 0.12)",
    chrome: "#0d1117",
    liveUrl: "https://github.com/topics/agent-skills",
    embed: "popup",
    kind: "repo",
  },
  "GitHub · Projects": {
    handle: "github-projects",
    domain: "github.com/topics/llm",
    mark: "GHp",
    accent: "#f0f6fc",
    accentSoft: "rgba(240, 246, 252, 0.08)",
    chrome: "#0d1117",
    liveUrl: "https://github.com/topics/llm",
    embed: "popup",
    kind: "repo",
  },
  "X (Twitter)": {
    handle: "x_ai_signal",
    domain: "x.com/explore",
    mark: "𝕏",
    accent: "#e7e9ea",
    accentSoft: "rgba(231, 233, 234, 0.08)",
    chrome: "#000000",
    liveUrl: "https://x.com/explore",
    embed: "popup",
    kind: "tweet",
  },
  YouTube: {
    handle: "YouTube",
    domain: "youtube.com/results?search_query=AI",
    mark: "▶",
    accent: "#ff0033",
    accentSoft: "rgba(255, 0, 51, 0.14)",
    chrome: "#0f0f0f",
    liveUrl: "https://www.youtube.com/results?search_query=artificial+intelligence",
    embed: "popup",
    kind: "youtube",
  },
  "Foreign Media": {
    handle: "wire",
    domain: "theverge.com/ai-artificial-intelligence",
    mark: "FM",
    accent: "#f5c518",
    accentSoft: "rgba(245, 197, 24, 0.12)",
    chrome: "#10100c",
    liveUrl: "https://www.theverge.com/ai-artificial-intelligence",
    embed: "popup",
    kind: "press",
  },
  "Embodied AI": {
    handle: "embodied",
    domain: "therobotreport.com",
    mark: "Emb",
    accent: "#5eead4",
    accentSoft: "rgba(94, 234, 212, 0.12)",
    chrome: "#0a1412",
    liveUrl: "https://www.therobotreport.com/",
    embed: "popup",
    kind: "press",
  },
  机器之心: {
    handle: "jiqizhixin",
    domain: "syncedreview.com",
    mark: "心",
    accent: "#3b82f6",
    accentSoft: "rgba(59, 130, 246, 0.14)",
    chrome: "#0c1220",
    liveUrl: "https://syncedreview.com/",
    embed: "popup",
    kind: "press",
  },
  新智元: {
    handle: "aiera",
    domain: "aiera.com.cn",
    mark: "智",
    accent: "#f59e0b",
    accentSoft: "rgba(245, 158, 11, 0.14)",
    chrome: "#14110a",
    liveUrl: "https://aiera.com.cn/",
    embed: "popup",
    kind: "press",
  },
  量子位: {
    handle: "qbitai",
    domain: "qbitai.com",
    mark: "量",
    accent: "#111111",
    accentSoft: "rgba(255, 255, 255, 0.08)",
    chrome: "#101010",
    liveUrl: "https://www.qbitai.com/",
    embed: "popup",
    kind: "press",
  },
  "Product Hunt": {
    handle: "producthunt",
    domain: "producthunt.com",
    mark: "PH",
    accent: "#da552f",
    accentSoft: "rgba(218, 85, 47, 0.14)",
    chrome: "#160e0c",
    liveUrl: "https://www.producthunt.com/topics/artificial-intelligence",
    embed: "popup",
    kind: "forum",
  },
};

export function openNativeSourceWindow(source: Source) {
  const chrome = sourceChrome[source];
  const width = 440;
  const height = 780;
  const left = Math.max(0, window.screenX + window.outerWidth - width - 24);
  const top = Math.max(0, window.screenY + 48);
  window.open(
    chrome.liveUrl,
    `signal-native-${source}`,
    `popup=yes,width=${width},height=${height},left=${left},top=${top},noopener,noreferrer`
  );
}
