import type { DeveloperCommunityRejectReason } from "@/lib/types";

const BOT_LOGIN =
  /(\[bot\]$|github-actions|dependabot|copilot|openhands|swe-agent|cursor-agent|claude-code-action)/i;

export function isBotAuthor(login?: string, type?: string): boolean {
  if (!login) return true;
  if (type === "Bot") return true;
  return BOT_LOGIN.test(login);
}

export function isPullRequest(payload: { pull_request?: unknown }): boolean {
  return payload.pull_request != null;
}

export function isFeatureRequest(title: string, body = ""): boolean {
  return (
    /^(feat(ure)?\b|\[feature\]|enhancement\b)/i.test(title.trim()) ||
    /\b(feature request|please add support|add support for)\b/i.test(
      `${title}\n${body}`
    )
  );
}

function mentionsConcreteRepro(text: string): boolean {
  if (/\bno repro\b/i.test(text)) return false;
  return /\b(repro|steps to reproduce|mcp-server|tool call|session)\b/i.test(text);
}

export function evidenceExclusion(
  title: string,
  body = "",
  options?: {
    sourceFamily?: "hn" | "github-issues";
    comments?: number;
    points?: number;
    stars?: number;
  }
): DeveloperCommunityRejectReason | undefined {
  const text = `${title}\n${body}`;
  if (
    /\b(as an ai|i am an ai|generated by|agent-coordination|ci alert|hourly routine|awos automated)\b/i.test(
      text
    ) ||
    (options?.comments ?? 0) >= 200
  ) {
    return "agent-spam";
  }
  if (options?.sourceFamily === "hn" && /^show hn\b/i.test(title.trim())) {
    return "show-hn-no-adoption";
  }
  if (/\b(hiring|job|we're hiring|who is hiring)\b/i.test(title)) {
    return "job-post";
  }
  if (
    /\b(benchmark|lmsys|leaderboard|arena elo)\b/i.test(text) &&
    !mentionsConcreteRepro(text)
  ) {
    return "benchmark-argument";
  }
  if (
    /\b(introducing |announcing |qwen 3\.8|glm-5\.3|frontier (?:coding|model))\b/i.test(
      text
    ) &&
    !mentionsConcreteRepro(text)
  ) {
    return "official-launch-repost";
  }
  if (
    /\b(techcrunch|the verge|mit technology review)\b/i.test(text) &&
    options?.sourceFamily === "hn"
  ) {
    return "media-repost";
  }
  if (
    /\b(how do i|getting started|what is mcp|beginner)\b/i.test(text) &&
    !mentionsConcreteRepro(text)
  ) {
    return "beginner-support";
  }
  if (
    /\b(windows: server fails to start when node\.js installed|left cli missing from path)\b/i.test(
      text
    ) ||
    (/\b(install|path|npm i|brew install)\b/i.test(text) &&
      !/\b(mcp|tool|session|stream)\b/i.test(text) &&
      options?.sourceFamily === "github-issues")
  ) {
    return "one-user-install";
  }
  if (
    options?.sourceFamily === "hn" &&
    /\b(feel worse|is dead|is amazing|hot take)\b/i.test(title) &&
    !mentionsConcreteRepro(text)
  ) {
    return "generic-opinion";
  }
  if (/\b(banned from claude|i was banned)\b/i.test(title)) {
    return "unsupported-claim";
  }
  if (/\b(99\.9%|fail the .{0,40}spec check)\b/i.test(title)) {
    return "unsupported-claim";
  }
  if (
    ((options?.stars ?? 0) >= 100_000 ||
      /\b\d[\d,.]*k?\s*stars\b/i.test(text)) &&
    !mentionsConcreteRepro(text)
  ) {
    return "star-inflation";
  }
  return undefined;
}

export function normalizeTitle(title: string): string {
  return title.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
}
